<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2020-09-11T22:12:29 BDT" name="Default suite" finished-at="2020-09-11T22:12:44 BDT" duration-ms="14823">
    <groups>
    </groups>
    <test started-at="2020-09-11T22:12:29 BDT" name="Default test" finished-at="2020-09-11T22:12:44 BDT" duration-ms="14823">
      <class name="com.newTest.NegativeTests">
        <test-method is-config="true" signature="setUp(java.lang.String)[pri:0, instance:com.newTest.NegativeTests@3098cf3b]" started-at="2020-09-11T22:12:30 BDT" name="setUp" finished-at="2020-09-11T22:12:37 BDT" duration-ms="7493" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA["chrome"]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="negativeTest(java.lang.String, java.lang.String, java.lang.String)[pri:1, instance:com.newTest.NegativeTests@3098cf3b]" started-at="2020-09-11T22:12:37 BDT" name="negativeTest" finished-at="2020-09-11T22:12:43 BDT" duration-ms="6383" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[param-val-not-found]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[param-val-not-found]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[param-val-not-found]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[actualErrorMessage does not contain expectedErrorMessage
expectedErrorMessage: param-val-not-found
actualErrorMessage: Your username is invalid!
× did not expect to find [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: actualErrorMessage does not contain expectedErrorMessage
expectedErrorMessage: param-val-not-found
actualErrorMessage: Your username is invalid!
× did not expect to find [true] but found [false]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.failNotEquals(Assert.java:969)
at org.testng.Assert.assertTrue(Assert.java:43)
at com.newTest.NegativeTests.negativeTest(NegativeTests.java:70)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- negativeTest -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.newTest.NegativeTests@3098cf3b]" started-at="2020-09-11T22:12:43 BDT" name="tearDown" finished-at="2020-09-11T22:12:44 BDT" duration-ms="873" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.newTest.NegativeTests -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
